# Generated by Django 5.2.3 on 2025-06-23 15:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('rent', 'إيجار'), ('deposit', 'تأمين'), ('maintenance', 'صيانة'), ('utilities', 'خدمات'), ('penalty', 'غرامة'), ('other', 'أخرى')], default='rent', help_text='نوع الدفعة', max_length=20, verbose_name='نوع الدفعة')),
                ('amount', models.DecimalField(decimal_places=3, help_text='مبلغ الدفعة بالريال العماني', max_digits=10, verbose_name='المبلغ')),
                ('due_date', models.DateField(help_text='تاريخ استحقاق الدفعة', verbose_name='تاريخ الاستحقاق')),
                ('payment_date', models.DateField(blank=True, help_text='تاريخ دفع المبلغ الفعلي', null=True, verbose_name='تاريخ الدفع')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'نقداً'), ('bank_transfer', 'تحويل بنكي'), ('check', 'شيك'), ('credit_card', 'بطاقة ائتمان'), ('online', 'دفع إلكتروني')], help_text='طريقة الدفع المستخدمة', max_length=20, null=True, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('paid', 'مدفوع'), ('overdue', 'متأخر'), ('cancelled', 'ملغى'), ('refunded', 'مسترد')], default='pending', help_text='حالة الدفعة الحالية', max_length=20, verbose_name='حالة الدفعة')),
                ('reference_number', models.CharField(blank=True, help_text='رقم مرجع الدفعة (رقم الشيك، رقم التحويل، إلخ)', max_length=100, null=True, verbose_name='رقم المرجع')),
                ('receipt_number', models.CharField(blank=True, help_text='رقم إيصال الدفعة', max_length=50, null=True, unique=True, verbose_name='رقم الإيصال')),
                ('late_fee', models.DecimalField(decimal_places=3, default=0, help_text='رسوم التأخير المضافة للدفعة', max_digits=10, verbose_name='رسوم التأخير')),
                ('discount', models.DecimalField(decimal_places=3, default=0, help_text='مبلغ الخصم المطبق على الدفعة', max_digits=10, verbose_name='الخصم')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات إضافية حول الدفعة', null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('lease', models.ForeignKey(help_text='عقد الإيجار المرتبط بالدفعة', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='leases.lease', verbose_name='عقد الإيجار')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(help_text='اسم وصفي لجدولة الدفعات', max_length=200, verbose_name='اسم الجدولة')),
                ('start_date', models.DateField(help_text='تاريخ بداية جدولة الدفعات', verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(help_text='تاريخ نهاية جدولة الدفعات', verbose_name='تاريخ النهاية')),
                ('payment_amount', models.DecimalField(decimal_places=3, help_text='مبلغ كل دفعة في الجدولة', max_digits=10, verbose_name='مبلغ الدفعة')),
                ('frequency_days', models.PositiveIntegerField(default=30, help_text='عدد الأيام بين كل دفعة', verbose_name='تكرار الدفع (أيام)')),
                ('is_active', models.BooleanField(default=True, help_text='هل الجدولة نشطة؟', verbose_name='نشط')),
                ('auto_generate', models.BooleanField(default=True, help_text='إنشاء الدفعات تلقائياً حسب الجدولة', verbose_name='إنشاء تلقائي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('lease', models.ForeignKey(help_text='عقد الإيجار المرتبط بالجدولة', on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='leases.lease', verbose_name='عقد الإيجار')),
            ],
            options={
                'verbose_name': 'جدولة دفعات',
                'verbose_name_plural': 'جدولة الدفعات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text='رقم الإيصال الفريد', max_length=50, unique=True, verbose_name='رقم الإيصال')),
                ('issued_date', models.DateField(default=datetime.date.today, help_text='تاريخ إصدار الإيصال', verbose_name='تاريخ الإصدار')),
                ('issued_by', models.CharField(help_text='اسم الشخص الذي أصدر الإيصال', max_length=200, verbose_name='أصدر بواسطة')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات إضافية على الإيصال', null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('payment', models.OneToOneField(help_text='الدفعة المرتبطة بالإيصال', on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.payment', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'إيصال',
                'verbose_name_plural': 'الإيصالات',
                'ordering': ['-issued_date'],
            },
        ),
    ]
