# Generated by Django 5.2.3 on 2025-06-23 15:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='الاسم الأول للمستأجر', max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(help_text='اسم العائلة للمستأجر', max_length=100, verbose_name='اسم العائلة')),
                ('national_id', models.CharField(help_text='الرقم المدني أو رقم البطاقة الشخصية', max_length=20, unique=True, verbose_name='الرقم المدني')),
                ('phone_number', models.CharField(help_text='رقم الهاتف للمستأجر', max_length=17, validators=[django.core.validators.RegexValidator(message="رقم الهاتف يجب أن يكون بالصيغة: '+999999999'. يُسمح بحد أقصى 15 رقم.", regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف')),
                ('email', models.EmailField(help_text='البريد الإلكتروني للمستأجر', max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(help_text='عنوان المستأجر الحالي', verbose_name='العنوان')),
                ('nationality', models.CharField(help_text='جنسية المستأجر', max_length=50, verbose_name='الجنسية')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], help_text='جنس المستأجر', max_length=10, verbose_name='الجنس')),
                ('date_of_birth', models.DateField(help_text='تاريخ ميلاد المستأجر', verbose_name='تاريخ الميلاد')),
                ('marital_status', models.CharField(choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], help_text='الحالة الاجتماعية للمستأجر', max_length=20, verbose_name='الحالة الاجتماعية')),
                ('occupation', models.CharField(blank=True, help_text='مهنة المستأجر', max_length=100, null=True, verbose_name='المهنة')),
                ('employer', models.CharField(blank=True, help_text='اسم جهة العمل', max_length=200, null=True, verbose_name='جهة العمل')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=3, help_text='الراتب الشهري بالريال العماني', max_digits=10, null=True, verbose_name='الراتب الشهري')),
                ('emergency_contact_name', models.CharField(help_text='اسم الشخص للاتصال به في حالات الطوارئ', max_length=200, verbose_name='اسم جهة الاتصال في حالات الطوارئ')),
                ('emergency_contact_phone', models.CharField(help_text='رقم هاتف جهة الاتصال في حالات الطوارئ', max_length=17, validators=[django.core.validators.RegexValidator(message="رقم الهاتف يجب أن يكون بالصيغة: '+999999999'. يُسمح بحد أقصى 15 رقم.", regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم هاتف جهة الاتصال في حالات الطوارئ')),
                ('emergency_contact_relationship', models.CharField(help_text='صلة القرابة مع جهة الاتصال في حالات الطوارئ', max_length=100, verbose_name='صلة القرابة مع جهة الاتصال')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات إضافية حول المستأجر', null=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, help_text='هل المستأجر نشط في النظام؟', verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(blank=True, help_text='ربط المستأجر بحساب مستخدم في النظام (اختياري)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مستأجر',
                'verbose_name_plural': 'المستأجرون',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_copy', 'نسخة من البطاقة الشخصية'), ('passport', 'نسخة من جواز السفر'), ('salary_certificate', 'شهادة راتب'), ('bank_statement', 'كشف حساب بنكي'), ('employment_letter', 'خطاب من جهة العمل'), ('other', 'أخرى')], help_text='نوع الوثيقة', max_length=50, verbose_name='نوع الوثيقة')),
                ('title', models.CharField(help_text='عنوان أو اسم الوثيقة', max_length=200, verbose_name='عنوان الوثيقة')),
                ('file', models.FileField(help_text='ملف الوثيقة', upload_to='tenant_documents/', verbose_name='الملف')),
                ('description', models.TextField(blank=True, help_text='وصف إضافي للوثيقة', null=True, verbose_name='الوصف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('tenant', models.ForeignKey(help_text='المستأجر الذي تنتمي إليه الوثيقة', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.tenant', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'وثيقة مستأجر',
                'verbose_name_plural': 'وثائق المستأجرين',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
