# Generated by Django 5.2.3 on 2025-06-23 15:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم فئة الصيانة', max_length=100, unique=True, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, help_text='وصف فئة الصيانة', null=True, verbose_name='الوصف')),
                ('default_priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', help_text='الأولوية الافتراضية لهذه الفئة', max_length=10, verbose_name='الأولوية الافتراضية')),
                ('estimated_duration_hours', models.PositiveIntegerField(default=2, help_text='المدة المقدرة لإنجاز هذا النوع من الصيانة', verbose_name='المدة المقدرة (ساعات)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فئة صيانة',
                'verbose_name_plural': 'فئات الصيانة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم الشركة أو الشخص مقدم خدمة الصيانة', max_length=200, verbose_name='اسم مقدم الخدمة')),
                ('contact_person', models.CharField(help_text='اسم الشخص المسؤول للتواصل', max_length=200, verbose_name='الشخص المسؤول')),
                ('phone_number', models.CharField(help_text='رقم هاتف مقدم الخدمة', max_length=17, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, help_text='البريد الإلكتروني لمقدم الخدمة', max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(help_text='عنوان مقدم الخدمة', verbose_name='العنوان')),
                ('rating', models.DecimalField(decimal_places=2, default=0, help_text='تقييم مقدم الخدمة من 0 إلى 5', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('is_active', models.BooleanField(default=True, help_text='هل مقدم الخدمة نشط؟', verbose_name='نشط')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات حول مقدم الخدمة', null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('specialties', models.ManyToManyField(help_text='تخصصات مقدم الخدمة', related_name='providers', to='maintenance.maintenancecategory', verbose_name='التخصصات')),
            ],
            options={
                'verbose_name': 'مقدم خدمة صيانة',
                'verbose_name_plural': 'مقدمو خدمات الصيانة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(help_text='رقم طلب الصيانة الفريد', max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('title', models.CharField(help_text='عنوان مختصر لطلب الصيانة', max_length=200, verbose_name='عنوان الطلب')),
                ('description', models.TextField(help_text='وصف تفصيلي للمشكلة أو الصيانة المطلوبة', verbose_name='وصف المشكلة')),
                ('category', models.CharField(choices=[('plumbing', 'سباكة'), ('electrical', 'كهرباء'), ('hvac', 'تكييف وتهوية'), ('appliances', 'أجهزة'), ('structural', 'إنشائية'), ('painting', 'دهان'), ('flooring', 'أرضيات'), ('doors_windows', 'أبواب ونوافذ'), ('cleaning', 'تنظيف'), ('pest_control', 'مكافحة حشرات'), ('security', 'أمن'), ('other', 'أخرى')], help_text='فئة نوع الصيانة المطلوبة', max_length=20, verbose_name='فئة الصيانة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', help_text='أولوية طلب الصيانة', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('submitted', 'مقدم'), ('acknowledged', 'مستلم'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغى'), ('on_hold', 'معلق')], default='submitted', help_text='الحالة الحالية لطلب الصيانة', max_length=20, verbose_name='حالة الطلب')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=3, help_text='التكلفة المقدرة للصيانة بالريال العماني', max_digits=10, null=True, verbose_name='التكلفة المقدرة')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=3, help_text='التكلفة الفعلية للصيانة بالريال العماني', max_digits=10, null=True, verbose_name='التكلفة الفعلية')),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='تاريخ ووقت الموعد المحدد للصيانة', null=True, verbose_name='تاريخ الموعد المحدد')),
                ('completed_date', models.DateTimeField(blank=True, help_text='تاريخ ووقت إكمال الصيانة', null=True, verbose_name='تاريخ الإكمال')),
                ('tenant_access_required', models.BooleanField(default=True, help_text='هل تتطلب الصيانة دخول الوحدة؟', verbose_name='يتطلب دخول المستأجر')),
                ('tenant_notified', models.BooleanField(default=False, help_text='هل تم إشعار المستأجر بالموعد؟', verbose_name='تم إشعار المستأجر')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات إضافية حول طلب الصيانة', null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='الشخص المكلف بتنفيذ الصيانة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='مكلف بالصيانة')),
                ('submitted_by', models.ForeignKey(help_text='المستخدم الذي قدم طلب الصيانة', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
                ('tenant', models.ForeignKey(blank=True, help_text='المستأجر الذي قدم الطلب (إذا كان من المستأجر)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='tenants.tenant', verbose_name='المستأجر')),
                ('unit', models.ForeignKey(help_text='الوحدة التي تحتاج صيانة', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='buildings.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'طلب صيانة',
                'verbose_name_plural': 'طلبات الصيانة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='صورة متعلقة بطلب الصيانة', upload_to='maintenance_photos/', verbose_name='الصورة')),
                ('photo_type', models.CharField(choices=[('before', 'قبل الصيانة'), ('during', 'أثناء الصيانة'), ('after', 'بعد الصيانة'), ('damage', 'ضرر'), ('parts', 'قطع غيار')], help_text='نوع الصورة', max_length=20, verbose_name='نوع الصورة')),
                ('description', models.CharField(blank=True, help_text='وصف مختصر للصورة', max_length=200, null=True, verbose_name='وصف الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('uploaded_by', models.ForeignKey(help_text='المستخدم الذي رفع الصورة', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_maintenance_photos', to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
                ('maintenance_request', models.ForeignKey(help_text='طلب الصيانة المرتبط بالصورة', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='maintenance.maintenancerequest', verbose_name='طلب الصيانة')),
            ],
            options={
                'verbose_name': 'صورة صيانة',
                'verbose_name_plural': 'صور الصيانة',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان الصيانة المجدولة', max_length=200, verbose_name='عنوان الجدولة')),
                ('description', models.TextField(help_text='وصف الصيانة المجدولة', verbose_name='الوصف')),
                ('frequency', models.CharField(choices=[('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('semi_annual', 'نصف سنوي'), ('annual', 'سنوي')], help_text='تكرار الصيانة', max_length=20, verbose_name='التكرار')),
                ('next_due_date', models.DateField(help_text='تاريخ الصيانة التالية المجدولة', verbose_name='تاريخ الاستحقاق التالي')),
                ('is_active', models.BooleanField(default=True, help_text='هل الجدولة نشطة؟', verbose_name='نشط')),
                ('auto_create_requests', models.BooleanField(default=True, help_text='إنشاء طلبات صيانة تلقائياً حسب الجدولة', verbose_name='إنشاء طلبات تلقائي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(help_text='فئة الصيانة المجدولة', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='maintenance.maintenancecategory', verbose_name='فئة الصيانة')),
                ('unit', models.ForeignKey(help_text='الوحدة المراد جدولة صيانتها', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='buildings.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'جدولة صيانة',
                'verbose_name_plural': 'جدولة الصيانة',
                'ordering': ['next_due_date'],
            },
        ),
    ]
