# Generated by Django 5.2.3 on 2025-06-23 15:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_number', models.CharField(help_text='رقم عقد الإيجار الفريد', max_length=50, unique=True, verbose_name='رقم العقد')),
                ('start_date', models.DateField(help_text='تاريخ بداية عقد الإيجار', verbose_name='تاريخ بداية العقد')),
                ('end_date', models.DateField(help_text='تاريخ انتهاء عقد الإيجار', verbose_name='تاريخ انتهاء العقد')),
                ('rent_amount', models.DecimalField(decimal_places=3, help_text='مبلغ الإيجار الشهري بالريال العماني', max_digits=10, verbose_name='مبلغ الإيجار الشهري')),
                ('deposit_amount', models.DecimalField(decimal_places=3, help_text='مبلغ التأمين المدفوع بالريال العماني', max_digits=10, verbose_name='مبلغ التأمين')),
                ('payment_frequency', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('semi_annual', 'نصف سنوي'), ('annual', 'سنوي')], default='monthly', help_text='تكرار دفع الإيجار', max_length=20, verbose_name='تكرار الدفع')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('expired', 'منتهي الصلاحية'), ('terminated', 'مفسوخ'), ('renewed', 'مجدد')], default='draft', help_text='الحالة الحالية للعقد', max_length=20, verbose_name='حالة العقد')),
                ('contract_file', models.FileField(blank=True, help_text='ملف عقد الإيجار الموقع', null=True, upload_to='lease_contracts/', verbose_name='ملف العقد')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='الشروط والأحكام الخاصة بالعقد', null=True, verbose_name='الشروط والأحكام')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات إضافية حول العقد', null=True, verbose_name='ملاحظات')),
                ('auto_renew', models.BooleanField(default=False, help_text='هل يتم تجديد العقد تلقائياً؟', verbose_name='التجديد التلقائي')),
                ('renewal_notice_days', models.PositiveIntegerField(default=30, help_text='عدد الأيام قبل انتهاء العقد لإرسال إشعار التجديد', verbose_name='أيام إشعار التجديد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('tenant', models.ForeignKey(help_text='المستأجر', on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='tenants.tenant', verbose_name='المستأجر')),
                ('unit', models.ForeignKey(help_text='الوحدة المؤجرة', on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='buildings.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'عقد إيجار',
                'verbose_name_plural': 'عقود الإيجار',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaseRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateField(default=datetime.date.today, help_text='تاريخ تجديد العقد', verbose_name='تاريخ التجديد')),
                ('rent_increase_percentage', models.DecimalField(decimal_places=2, default=0, help_text='نسبة زيادة الإيجار عند التجديد', max_digits=5, verbose_name='نسبة زيادة الإيجار (%)')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات حول التجديد', null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('new_lease', models.OneToOneField(help_text='العقد الجديد بعد التجديد', on_delete=django.db.models.deletion.CASCADE, related_name='renewal_record', to='leases.lease', verbose_name='العقد الجديد')),
                ('original_lease', models.ForeignKey(help_text='العقد الأصلي المراد تجديده', on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='leases.lease', verbose_name='العقد الأصلي')),
            ],
            options={
                'verbose_name': 'تجديد عقد',
                'verbose_name_plural': 'تجديدات العقود',
                'ordering': ['-renewal_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaseTermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_date', models.DateField(help_text='تاريخ إنهاء العقد', verbose_name='تاريخ الإنهاء')),
                ('reason', models.CharField(choices=[('tenant_request', 'طلب من المستأجر'), ('owner_request', 'طلب من المالك'), ('breach_of_contract', 'مخالفة شروط العقد'), ('non_payment', 'عدم دفع الإيجار'), ('property_sale', 'بيع العقار'), ('renovation', 'تجديد العقار'), ('other', 'أخرى')], help_text='سبب إنهاء العقد', max_length=50, verbose_name='سبب الإنهاء')),
                ('notice_period_days', models.PositiveIntegerField(default=30, help_text='فترة الإشعار المطلوبة قبل الإنهاء', verbose_name='فترة الإشعار (أيام)')),
                ('penalty_amount', models.DecimalField(decimal_places=3, default=0, help_text='مبلغ الغرامة المترتبة على الإنهاء المبكر', max_digits=10, verbose_name='مبلغ الغرامة')),
                ('deposit_refund_amount', models.DecimalField(decimal_places=3, default=0, help_text='مبلغ التأمين المسترد للمستأجر', max_digits=10, verbose_name='مبلغ استرداد التأمين')),
                ('notes', models.TextField(blank=True, help_text='ملاحظات حول إنهاء العقد', null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('lease', models.OneToOneField(help_text='العقد المراد إنهاؤه', on_delete=django.db.models.deletion.CASCADE, related_name='termination', to='leases.lease', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'إنهاء عقد',
                'verbose_name_plural': 'إنهاءات العقود',
                'ordering': ['-termination_date'],
            },
        ),
    ]
