# Generated by Django 5.2.3 on 2025-06-23 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم المبنى التجاري', max_length=200, verbose_name='اسم المبنى')),
                ('address', models.TextField(help_text='العنوان الكامل للمبنى', verbose_name='العنوان')),
                ('description', models.TextField(blank=True, help_text='وصف تفصيلي للمبنى وخدماته', null=True, verbose_name='الوصف')),
                ('total_floors', models.PositiveIntegerField(default=1, help_text='العدد الإجمالي للطوابق في المبنى', verbose_name='إجمالي الطوابق')),
                ('has_mosque', models.BooleanField(default=False, help_text='هل يحتوي المبنى على مصلى؟', verbose_name='يحتوي على مصلى')),
                ('has_elevator', models.BooleanField(default=False, help_text='هل يحتوي المبنى على مصعد؟', verbose_name='يحتوي على مصعد')),
                ('has_parking', models.BooleanField(default=False, help_text='هل يحتوي المبنى على مواقف سيارات؟', verbose_name='يحتوي على مواقف')),
                ('parking_spaces', models.PositiveIntegerField(default=0, help_text='عدد مواقف السيارات المتاحة', verbose_name='عدد مواقف السيارات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مبنى',
                'verbose_name_plural': 'المباني',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نوع الوحدة (مثل: شقة، مكتب، محل تجاري)', max_length=100, unique=True, verbose_name='اسم نوع الوحدة')),
                ('description', models.TextField(blank=True, help_text='وصف نوع الوحدة', null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'نوع الوحدة',
                'verbose_name_plural': 'أنواع الوحدات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(help_text='رقم الطابق (0 للطابق الأرضي، 1 للطابق الأول، إلخ)', verbose_name='رقم الطابق')),
                ('name', models.CharField(help_text='اسم الطابق (مثل: الطابق الأرضي، الطابق الأول)', max_length=100, verbose_name='اسم الطابق')),
                ('description', models.TextField(blank=True, help_text='وصف إضافي للطابق', null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('building', models.ForeignKey(help_text='المبنى الذي ينتمي إليه الطابق', on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='buildings.building', verbose_name='المبنى')),
            ],
            options={
                'verbose_name': 'طابق',
                'verbose_name_plural': 'الطوابق',
                'ordering': ['building', 'floor_number'],
                'unique_together': {('building', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(help_text='رقم الوحدة أو الشقة', max_length=20, verbose_name='رقم الوحدة')),
                ('area', models.DecimalField(decimal_places=2, help_text='مساحة الوحدة بالمتر المربع', max_digits=10, verbose_name='المساحة (متر مربع)')),
                ('rent_price', models.DecimalField(decimal_places=3, help_text='سعر الإيجار الشهري بالريال العماني', max_digits=10, verbose_name='سعر الإيجار الشهري')),
                ('status', models.CharField(choices=[('vacant', 'شاغرة'), ('rented', 'مؤجرة'), ('maintenance', 'تحت الصيانة'), ('reserved', 'محجوزة')], default='vacant', help_text='الحالة الحالية للوحدة', max_length=20, verbose_name='حالة الوحدة')),
                ('description', models.TextField(blank=True, help_text='وصف تفصيلي للوحدة ومميزاتها', null=True, verbose_name='الوصف')),
                ('bedrooms', models.PositiveIntegerField(default=0, help_text='عدد غرف النوم (للشقق السكنية)', verbose_name='عدد غرف النوم')),
                ('bathrooms', models.PositiveIntegerField(default=1, help_text='عدد دورات المياه', verbose_name='عدد دورات المياه')),
                ('has_balcony', models.BooleanField(default=False, help_text='هل تحتوي الوحدة على شرفة؟', verbose_name='يحتوي على شرفة')),
                ('has_kitchen', models.BooleanField(default=True, help_text='هل تحتوي الوحدة على مطبخ؟', verbose_name='يحتوي على مطبخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('floor', models.ForeignKey(help_text='الطابق الذي تقع فيه الوحدة', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='buildings.floor', verbose_name='الطابق')),
                ('unit_type', models.ForeignKey(help_text='نوع الوحدة', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='buildings.unittype', verbose_name='نوع الوحدة')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
                'ordering': ['floor__building', 'floor__floor_number', 'unit_number'],
                'unique_together': {('floor', 'unit_number')},
            },
        ),
    ]
